
all : ipc_producer2 ipc_consumer2

ipc_producer : ipc_producer.c
	gcc -Wall -o ipc_producer2 ipc_producer2.c

ipc_consumer : ipc_consumer.c
	gcc -Wall -o ipc_consumer2 ipc_consumer2.c

clean :
	rm ipc_producer2 ipc_consumer2
