
all : ipc_producer4 ipc_consumer4

ipc_producer4 : ipc_producer4.c
	gcc -Wall -o ipc_producer4 ipc_producer4.c

ipc_consumer4 : ipc_consumer4.c
	gcc -Wall -o ipc_consumer4 ipc_consumer4.c

clean : 
	rm ipc_producer4 ipc_consumer4 
